server:
  port: 8090
spring:
#  profiles:
#    active: dev
  datasource:
    username: houyu1124
    password: houyu07181
    url: jdbc:mysql://localhost:3307/learning_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  flyway:
    # 是否启用flyway
    enabled: false
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:database/flyway
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: houyu07181
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 3000MB
      file-size-threshold: 512KB
      location: /
app:
  jwtExpirationAt: 86400000
  secret: JKKLJOoasdlfj
  auther: houyu
path:
  uploadPath: file:///
  videoPath: C:\Users\graduation_Project\video\
  imagePath: C:\Users\graduation_Project\image\
# feign相关配置
feign:
  # Feign org.springframework.data.domain.Page编码和解码
  # Feign org.springframework.data.domain.Sort编码解码
  autoconfiguration:
    jackson:
      # 如果为true，则将提供PageJacksonModule、SortJacksonModule用jackson对Page进行编码和解码操作，默认：false
      enabled: true