server:
  port: 8090
spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/learning_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 3000MB
      file-size-threshold: 512KB
      location: /
  web:
    resources:
      static-locations: file:${oss.local.upload-file-path}
path:
  uploadPath: http://localhost:8090
app:
  jwtExpirationAt: 86400000
  secret: JKKLJOoasdlfj
  auther: houyu
oss:
  client-type: local
  #默认上传目录
  base_dir:
  #允许的文件扩展名
  allowed_extension: mp4,bmp, gif, jpg, jpeg, png,doc, docx, xls, xlsx, ppt, pptx,html,htm,txt,rar, zip, gz, bz2,pdf
  #最大文件大小 50M
  max_size: 52428800
  local:
    domain: 本地地址
#    upload-file-path: /root/graduate_project
    upload-file-path: E:/graduation_Project

# feign相关配置
feign:
  # Feign org.springframework.data.domain.Page编码和解码
  # Feign org.springframework.data.domain.Sort编码解码
  autoconfiguration:
    jackson:
      # 如果为true，则将提供PageJacksonModule、SortJacksonModule用jackson对Page进行编码和解码操作，默认：false
      enabled: true
